### ISSUE TITLE
How can I initially have the drawer open? 

### ISSUE THREAD

**Issue by Josua2012** [NikhilVadoliya/Flutter_slider_drawer#11] opened 2021-03-07 14:00 UTC
Hi,
I have tried having the drawer initially open, but have not seen the possibility.
You can tell me how to do it and if I can't, you can implement this functionality.
Thanks. 

Regards,
Jose.

**Comment by NikhilVadoliya** [comment] 2021-04-10 07:29
Duplicate of #12

**Closed by NikhilVadoliya** 2021-04-10 07:29 UTC
